-- user privileges
CREATE USER IF NOT EXISTS 'proponleZacAdm'@'localhost' IDENTIFIED BY '>GD2R3,(<xj8m:<a';
CREATE USER IF NOT EXISTS 'proponleZacUsr'@'localhost' IDENTIFIED BY 'uxU2j*6gXVTT;_#7';
CREATE USER IF NOT EXISTS 'proponleZacConsulta'@'localhost' IDENTIFIED BY '!<x8KS@CKKbx=gWF';
GRANT SELECT ON proponleZac.*  TO 'proponleZacConsulta'@'localhost';
GRANT EXECUTE ON PROCEDURE proponleZac.debatesList TO 'proponleZacConsulta'@'localhost';
GRANT SELECT,INSERT,UPDATE,DELETE ON proponleZac.* TO 'proponleZacUsr'@'localhost';
GRANT EXECUTE ON PROCEDURE proponleZac.insertarEtiquetas TO 'proponleZacUsr'@'localhost';
GRANT EXECUTE ON PROCEDURE proponleZac.insertarDebate TO 'proponleZacUsr'@'localhost';
GRANT EXECUTE ON PROCEDURE proponleZac.registrosDebates TO 'proponleZacConsulta'@'localhost';
GRANT EXECUTE ON PROCEDURE proponleZac.etiquetasVisitadas TO 'proponleZacConsulta'@'localhost';
GRANT EXECUTE ON PROCEDURE proponleZac.registroUsuario TO 'proponleZacUsr'@'localhost';
GRANT EXECUTE ON PROCEDURE proponleZac.usuarios TO 'proponleZacConsulta'@'localhost';
GRANT EXECUTE ON PROCEDURE proponleZac.infoUsuario TO 'proponleZacConsulta'@'localhost';
GRANT EXECUTE ON PROCEDURE proponleZac.tagsDebate TO 'proponleZacConsulta'@'localhost';
GRANT EXECUTE ON PROCEDURE proponleZac.registrarVoto TO 'proponleZacUsr'@'localhost';
GRANT EXECUTE ON PROCEDURE proponleZac.buscarVoto TO 'proponleZacConsulta'@'localhost';
GRANT EXECUTE ON PROCEDURE proponleZac.comentarios TO 'proponleZacConsulta'@'localhost';
GRANT EXECUTE ON PROCEDURE proponleZac.propuestasList TO 'proponleZacConsulta'@'localhost';
GRANT EXECUTE ON PROCEDURE proponleZac.registrosPropuestas TO 'proponleZacConsulta'@'localhost';
GRANT EXECUTE ON PROCEDURE proponleZac.categoriasVisitadas TO 'proponleZacConsulta'@'localhost';
GRANT EXECUTE ON PROCEDURE proponleZac.votoPropuesta TO 'proponleZacUsr'@'localhost';
GRANT execute ON procedure proponleZac.insertarPropuesta TO 'proponleZacUsr'@'localhost';
FLUSH PRIVILEGES;
